---

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined
  tags:
    - environment-setup
    - database
    - redis

- name: Ensure Redis is installed.
  apt:
    name: "{{ redis_package }}"
    state: present
  tags:
    - environment-setup
    - database
    - redis
  
- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
  tags:
    - environment-setup
    - database
    - redis
